name: cop26
channels:
  - conda-forge
  - defaults
dependencies:
  - folium
  - geopandas
  - jupyterlab
  - matplotlib
  - numpy
  - OWSLib
  - pandas
  - python >= 3.8
  - requests
  - seaborn
  - shapely
